# Generated by Django 5.1.15 on 2026-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="signature",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
