# Generated by Django 5.1.15 on 2026-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshcredential",
            name="jump_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sshcredential",
            name="jump_port",
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name="sshcredential",
            name="jump_username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
