# Generated by Django 5.1.15 on 2026-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sshcredential_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "平台管理员"),
                    ("operator", "运维员"),
                    ("viewer", "只读"),
                    ("enterprise_admin", "企业管理员"),
                    ("enterprise_user", "企业员工"),
                ],
                default="operator",
                max_length=20,
            ),
        ),
    ]
