# Generated by Django 5.1.15 on 2026-08-09 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("scripts", "0001_initial"),
        ("servers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InitTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion_check_script",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"script_type": "completion_check"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scripts.script",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_check_script",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"script_type": "health_check"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scripts.script",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="init_templates",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InitJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("connectivity", "连通性检查"),
                            ("health", "健康检查"),
                            ("init", "初始化"),
                            ("completion", "完成度检查"),
                        ],
                        default="connectivity",
                        max_length=20,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="servers.servergroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="init_jobs",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="tasks.inittemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobServerTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("connectivity_result", models.JSONField(blank=True, default=dict)),
                ("health_result", models.JSONField(blank=True, default=dict)),
                ("completion_result", models.JSONField(blank=True, default=dict)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.PositiveIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_tasks",
                        to="tasks.initjob",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["server__hostname"],
            },
        ),
        migrations.CreateModel(
            name="TaskStepLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phase", models.CharField(max_length=20)),
                ("step_order", models.PositiveIntegerField(blank=True, null=True)),
                ("script_name", models.CharField(blank=True, max_length=200)),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "server_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_logs",
                        to="tasks.jobservertask",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_order", models.PositiveIntegerField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=600)),
                (
                    "on_failure",
                    models.CharField(
                        choices=[
                            ("abort", "中断"),
                            ("continue", "继续"),
                            ("retry", "重试"),
                        ],
                        default="abort",
                        max_length=10,
                    ),
                ),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="scripts.script",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tasks.inittemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
                "unique_together": {("template", "step_order")},
            },
        ),
    ]
