# Generated by Django 5.1.15 on 2026-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobservertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "运行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("timeout", "超时"),
                    ("cancelled", "已取消"),
                    ("skipped", "跳过"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
