# Generated by Django 5.1.15 on 2026-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_jobservertask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inittemplate",
            name="webhook_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
