# Generated by Django 5.1.15 on 2026-08-15 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sshcredential_extra_fields"),
        ("servers", "0009_alter_server_connectivity_status_and_more"),
        ("tasks", "0003_inittemplate_webhook_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="initjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "运行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobservertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "运行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("timeout", "超时"),
                    ("cancelled", "已取消"),
                    ("skipped", "跳过"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="initjob",
            index=models.Index(
                fields=["tenant", "-created_at"], name="tasks_initj_tenant__6abe45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initjob",
            index=models.Index(
                fields=["tenant", "status"], name="tasks_initj_tenant__37db1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobservertask",
            index=models.Index(
                fields=["job", "status"], name="tasks_jobse_job_id_232116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasksteplog",
            index=models.Index(
                fields=["server_task", "phase"], name="tasks_tasks_server__093b17_idx"
            ),
        ),
    ]
