# Generated by Django 5.1.15 on 2026-08-17 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_extend_user_roles"),
        ("tasks", "0004_alter_initjob_status_alter_jobservertask_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "紧急"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "response_minutes",
                    models.PositiveIntegerField(help_text="响应时限（分钟）"),
                ),
                (
                    "resolve_minutes",
                    models.PositiveIntegerField(help_text="处理时限（分钟）"),
                ),
                (
                    "escalation_rules",
                    models.JSONField(
                        blank=True, default=dict, help_text="超时升级规则"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SLA策略",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_no",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fault", "故障"),
                            ("request", "需求"),
                            ("internal", "内部请求"),
                            ("change", "变更"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "紧急"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待受理"),
                            ("assigned", "已分派"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("closed", "已关闭"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True, help_text="首次响应时间", null=True
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="首次分派时间", null=True
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="解决时间", null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, help_text="关闭时间", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="tasks.initjob",
                    ),
                ),
                (
                    "sla_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="tickets.slapolicy",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "工单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="ticket_attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(help_text="文件大小（字节）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "附件",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_system",
                    models.BooleanField(default=False, help_text="系统自动评论"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "工单评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("fault", "故障"),
                            ("request", "需求"),
                            ("internal", "内部请求"),
                            ("change", "变更"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_flows",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "流转模板",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField()),
                (
                    "role_required",
                    models.CharField(
                        choices=[
                            ("admin", "平台管理员"),
                            ("operator", "运维员"),
                            ("enterprise_admin", "企业管理员"),
                        ],
                        default="operator",
                        max_length=20,
                    ),
                ),
                ("is_terminal", models.BooleanField(default=False)),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        default=8, help_text="节点处理时限（小时）"
                    ),
                ),
                (
                    "auto_assign_rule",
                    models.CharField(
                        choices=[
                            ("manual", "手动"),
                            ("round_robin", "轮询"),
                            ("least_load", "最少负载"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="tickets.ticketflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程节点",
                "ordering": ["flow", "order"],
                "unique_together": {("flow", "order")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tickets.ticketnode",
            ),
        ),
        migrations.CreateModel(
            name="TicketTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="在源节点停留时长（秒）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tickets.ticketnode",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tickets.ticketnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "流转记录",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "工单创建"),
                            ("ticket_assigned", "工单分派"),
                            ("ticket_transition", "工单流转"),
                            ("ticket_resolved", "工单解决"),
                            ("ticket_closed", "工单关闭"),
                            ("sla_warning", "SLA预警"),
                            ("sla_violated", "SLA违规"),
                            ("ticket_comment", "工单评论"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="tickets_not_user_id_977764_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "status"], name="tickets_tic_tenant__c58352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "-created_at"], name="tickets_tic_tenant__b8ec90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assignee", "status"], name="tickets_tic_assigne_294cb9_idx"
            ),
        ),
    ]
