# Generated by Django 5.1.15 on 2026-08-17 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("fault", "故障"),
                            ("request", "需求"),
                            ("internal", "内部请求"),
                            ("change", "变更"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="自定义字段定义"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "工单模板",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
