# Generated by Django 5.1.15 on 2026-08-12 06:08
# 注意：部署前需确保 Server 表无重复 IP（否则 AlterField unique 迁移失败）。
# 可在迁移前执行：SELECT ip, COUNT(*) FROM servers_server GROUP BY ip HAVING COUNT(*) > 1;
# 并人工处理重复记录。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0006_remove_server_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
