# Generated by Django 5.1.15 on 2026-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0007_alter_server_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="auth_password_encrypted",
            field=models.BinaryField(
                blank=True, help_text="内联密码（加密存储）", null=True
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="auth_private_key_encrypted",
            field=models.BinaryField(
                blank=True, help_text="内联私钥（加密存储）", null=True
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("credential", "使用凭据"),
                    ("password", "密码"),
                    ("key", "私钥"),
                ],
                default="credential",
                help_text="认证方式：credential=使用已有凭据；password=直接用户名密码；key=直接用户名+私钥",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="auth_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
