# Generated by Django 5.1.15 on 2026-08-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0008_server_auth_password_encrypted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="connectivity_status",
            field=models.CharField(
                choices=[("unknown", "未知"), ("success", "连通"), ("failed", "失败")],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="hostname",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
